import img1 from './image5.png'
import img2 from './home.png'
import img3 from './briefcase.png'
import img4 from './task.png'
import img5 from './receipt-item.png'
import img6 from './Chart_Pie.png'
import img7 from './Settings_Future.png'
import img8 from './Settings_Future.png'
import img9 from './Avatar.jpg'
import img10 from './Search.jpg'
import img11 from './settings.svg'
import img12 from './bell.svg'
import img13 from './export.png'
import img14 from './plus.svg'
import img15 from './no-active.svg'
import img16 from './briefcase.svg'
import img17 from './close.svg'
import img18 from './Path.svg'
import img19 from './Oval.svg'

export{img1,img2,img3,img4,img5,img6,img7,img8,img9,img10,img11,img12,img13,img14,img15,img16,img17,img18,img19}