import img1 from './image5.png'
import img2 from './home.png'
import img3 from './briefcase.png'
import img4 from './task.png'
import img5 from './receipt-item.png'
import img6 from './Chart_Pie.png'
import img7 from './Settings_Future.png'
import img8 from './Settings_Future.png'
import img9 from './Avatar.jpg'
import img10 from './Search.jpg'
import img11 from './settings.svg'
import img12 from './bell.svg'
import img13 from './export.png'
import img14 from './plus.svg'
import img15 from './no-active.svg'
import img16 from './briefcase.svg'
import img17 from './close.svg'
import img18 from './Path.svg'
import img19 from './Oval.svg'
import img20 from './edit.svg'
import img21 from './Filters.svg'
import img22 from './element.svg'
import img23 from './help-circle.svg'
import img24 from './_Dot.svg'
import img25 from './Success.svg'
import img26 from './Off.svg'
import img27 from './Ovalist.svg'
import img28 from './arrow-down.svg'
import img29 from './Dot-grey.svg'


export{img1,img2,img3,img4,img5,img6,img7,img8,
    img9,img10,img11,img12,img13,img14,img15,img16,
    img17,img18,img19, img20,img21,img22,img23, img24,img25,img26,img27, img28, img29}